spring:
  application:
    name: aidemo
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/aidemo
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:database/schema/master.xml
logging:
  level:
    dev:
      langchain4j: DEBUG
