version: "3.2"
services:
  db:
    image: postgres:12.20-alpine
    container_name: db-aidemo-ollama
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aidemo
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
  ollama-server:
    image: ollama/ollama:0.3.12
    container_name: ollama-aidemo
    ports:
      - "11434:11434"
    volumes:
      - /root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    tty: true
    restart: always
    environment:
      AIOHTTP_CLIENT_TIMEOUT: 1200
      DEFAULT_REQUEST_TIMEOUT: 1200
    entrypoint: [ "/usr/bin/bash", "/entrypoint.sh" ]