version: "3.2"
services:
  db:
    image: postgres
    container_name: db-aidemo-chatgpt
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aidemo
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10